version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sakanbeer88/hsr-data-analyzer:latest
    ports:
      - "1234:1234"
    volumes:
      - ./visual_img:/app/hsrws/visual/visual_img
    environment:
      - USER_AGENT=
    command: ["gunicorn", "--bind", "0.0.0.0:1234", "main:app"]