{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Seele Talents\",\"Errors in Seele Talents\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Characters\",\"Stats\",\"Parameter2\",\"Transform Sample File (2)\",\"Sample File (2)\",\"Transform File (2)\",\"Level\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.1261.0 (24.02)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Errors in Seele Talents",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Source = #\"Seele Talents\",",
          "  #\"Detected Type Mismatches\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Source, pairs),",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Level\", \"Basic ATK (DMG%)\", \"Skill (DMG%)\", \"Ultimate(DMG%)\", \"Talent (DMG%)\", \"Basic ATK (DMG%) Growth %\", \"Skill (DMG%) Growth%\", \"Ultimate(DMG%) Growth%\", \"Talent (DMG%) Growth %\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Level\", \"Basic ATK (DMG%)\", \"Skill (DMG%)\", \"Ultimate(DMG%)\", \"Talent (DMG%)\", \"Basic ATK (DMG%) Growth %\", \"Skill (DMG%) Growth%\", \"Ultimate(DMG%) Growth%\", \"Talent (DMG%) Growth %\"})",
          "in",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "2b00ab64-470a-4fbc-a39b-06294cf54854",
        "queryGroup": "Query Errors - 15/11/2566 1:50:09"
      },
      {
        "name": "Seele Talents",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sakan\\Desktop\\DA\\Book1.xlsx\"), null, true),",
          "    #\"Seele Talents_Sheet\" = Source{[Item=\"Seele Talents\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Seele Talents_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Level\", Int64.Type}, {\"Basic ATK (DMG%)\", Int64.Type}, {\"Skill (DMG%)\", type number}, {\"Ultimate(DMG%)\", type number}, {\"Talent (DMG%)\", Int64.Type}, {\"Basic ATK (DMG%) Growth %\", type number}, {\"Skill (DMG%) Growth%\", type number}, {\"Ultimate(DMG%) Growth%\", type number}, {\"Talent (DMG%) Growth %\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "a9a46ae7-1b60-4fb8-a801-8488b39ba3c1"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "ab21d6e3-8441-4d33-aae7-6348f3d9fb99",
        "queryGroup": "Transform File from hsr_updated\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "98866269-6f52-40bc-9571-0d225970c4e1",
        "queryGroup": "Transform File from hsr_updated"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"D:\\DA\\Honkai Star Rail Fun Insights from Data Analysis\\Honkai-Star-Rail-A-Few-Fun-Insights-with-Data-Analysis\\hsr\\hsr_updated\")",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "42c00001-380e-4c97-b786-44d67e52e26b",
        "queryGroup": "Transform File from hsr_updated\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "99a24242-e603-4873-8b45-33e7ab63483b",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from hsr_updated\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter2, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "18338687-76b0-483e-b3da-0758176b1c40",
        "queryGroup": "Transform File from hsr_updated (2)"
      },
      {
        "name": "Parameter2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4b93ef23-d4d9-4251-bc96-e45ee1947cf0",
        "queryGroup": "Transform File from hsr_updated (2)\\Helper Queries"
      },
      {
        "name": "Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"D:\\DA\\Honkai Star Rail Fun Insights from Data Analysis\\Honkai-Star-Rail-A-Few-Fun-Insights-with-Data-Analysis\\hsr\\hsr_updated\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "ae92cdef-a3a3-4c05-9527-a8d5b62e1def",
        "queryGroup": "Transform File from hsr_updated (2)\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "    Source = Excel.Workbook(Parameter2, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "9285b6f7-85d9-4c65-a177-10544197a2a8",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (2)\"\"}\" ]",
        "queryGroup": "Transform File from hsr_updated (2)\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 15/11/2566 1:50:09.",
        "folder": "Query Errors - 15/11/2566 1:50:09"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Transform File from hsr_updated"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from hsr_updated\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Transform File from hsr_updated (2)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from hsr_updated (2)\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "66e3d2f5-78bd-4beb-b795-c3cf4fd63fa7",
        "fromColumn": "CharacterId",
        "fromTable": "Stats",
        "toColumn": "CharacterId",
        "toTable": "Characters"
      },
      {
        "name": "a0411b4d-2e3d-45bd-b2e4-71169d5d6943",
        "fromColumn": "Level_Id",
        "fromTable": "Stats",
        "toColumn": "Level_Id",
        "toTable": "Level"
      }
    ],
    "sourceQueryCulture": "th-TH",
    "tables": [
      {
        "name": "DateTableTemplate_5bd3eaf3-9008-49f8-a265-4236ce5faed4",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3a6f5e6c-ed3b-41b1-94c2-b289a2544fc4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ae35c406-208a-484a-856a-499afa300310",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "61828583-4e62-48c4-ac4e-00f7e9442444",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9345545e-649a-4514-b323-e296f6d5e9a6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "34acbed3-12c2-48f1-98a3-b5cfa4225205",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7e650be3-1e08-49ba-9d32-55114942bef9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "20b1b50b-e31a-4444-8163-6ffa00d03163",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4adb264f-2d73-4ff4-aa23-54abe1a031cd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a8684077-245b-464f-8d65-5624966bef46",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "620797f5-eecc-4af3-849a-11372c635f4a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "68e1300c-a829-4f07-8849-ef7babfb2269",
                "ordinal": 3
              }
            ],
            "lineageTag": "036ff32a-c1b3-4087-b37e-b1c4e58e617d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1b15a23c-6a72-4960-a150-d5e12c27af34",
        "partitions": [
          {
            "name": "DateTableTemplate_5bd3eaf3-9008-49f8-a265-4236ce5faed4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Characters",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Character",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "095bee4d-e14b-4215-92d7-1716223d1560",
            "sourceColumn": "Character",
            "summarizeBy": "none"
          },
          {
            "name": "Path",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65f1e709-05cd-4df7-93b0-b4125b87d19a",
            "sourceColumn": "Path",
            "summarizeBy": "none"
          },
          {
            "name": "Rarity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8cc378b-c9dc-4aa0-920c-f444a80dc0d6",
            "sourceColumn": "Rarity",
            "summarizeBy": "none"
          },
          {
            "name": "Element",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "887e2188-f936-408c-b496-5b190588380a",
            "sourceColumn": "Element",
            "summarizeBy": "none"
          },
          {
            "name": "CharacterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "2ac81ef3-6c19-4343-8a84-2704d607f76e",
            "sourceColumn": "CharacterId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6c2f9e81-e479-4304-bfad-91c5670c63bd",
        "partitions": [
          {
            "name": "Characters",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"D:\\DA\\Honkai Star Rail Fun Insights from Data Analysis\\Honkai-Star-Rail-A-Few-Fun-Insights-with-Data-Analysis\\data\\hsr_paths_rarities_elements.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Character\", type text}, {\"Path\", type text}, {\"Rarity\", Int64.Type}, {\"Element\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"CharacterId\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"CharacterId\", \"Character\", \"Path\", \"Rarity\", \"Element\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Stats",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "HP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95126524-3680-46d7-af4f-57bcaa9d936a",
            "sourceColumn": "HP",
            "summarizeBy": "sum"
          },
          {
            "name": "ATK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3140083-b8b4-4657-a82c-6a6b3814163f",
            "sourceColumn": "ATK",
            "summarizeBy": "sum"
          },
          {
            "name": "DEF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5eeb5356-7208-48dc-81f6-aba9e7764250",
            "sourceColumn": "DEF",
            "summarizeBy": "sum"
          },
          {
            "name": "Speed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a044548-b1e9-40de-92e5-18a50c1d657c",
            "sourceColumn": "Speed",
            "summarizeBy": "sum"
          },
          {
            "name": "ATK Growth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8dd2c634-2682-4b81-863f-b87906bfa98b",
            "sourceColumn": "ATK Growth",
            "summarizeBy": "sum"
          },
          {
            "name": "ATK Growth %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9bb5d98c-41b3-4bb7-a9bc-25dd2482fd81",
            "sourceColumn": "ATK Growth %",
            "summarizeBy": "sum"
          },
          {
            "name": "DEF Growth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2c0e3180-34fa-4599-a2bf-7e00c2ffe3e7",
            "sourceColumn": "DEF Growth",
            "summarizeBy": "sum"
          },
          {
            "name": "DEF Growth %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fa44d15d-1959-40a2-856f-98bca4499f33",
            "sourceColumn": "DEF Growth %",
            "summarizeBy": "sum"
          },
          {
            "name": "HP Growth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24e5b986-a1a0-4404-948c-d5c638208de1",
            "sourceColumn": "HP Growth",
            "summarizeBy": "sum"
          },
          {
            "name": "HP Growth %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "070efd6b-adf2-476e-819d-593e0f3f1531",
            "sourceColumn": "HP Growth %",
            "summarizeBy": "sum"
          },
          {
            "name": "Speed Growth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd949d8c-9b08-4d78-be0a-0fa2a7352c77",
            "sourceColumn": "Speed Growth",
            "summarizeBy": "sum"
          },
          {
            "name": "Speed Growth %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0%;-0%;0%",
            "lineageTag": "6dc1ac9b-7b7b-4ce8-ba7a-945b88d332d0",
            "sourceColumn": "Speed Growth %",
            "summarizeBy": "sum"
          },
          {
            "name": "Stat Sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Stats'[DEF] + 'Stats'[ATK] + 'Stats'[HP] + 'Stats'[Speed]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8d141187-2c0b-4473-9ac4-186e5e9ea9f4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CharacterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a8e7db2-0935-4168-aa05-b2026fe8991f",
            "sourceColumn": "CharacterId",
            "summarizeBy": "none"
          },
          {
            "name": "Level_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "267984cb-18e6-48f2-a857-e12f2699b606",
            "sourceColumn": "Level_Id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "102a74e2-aa80-467e-a6e8-ffdec2a978e4",
        "measures": [
          {
            "name": "Sum All Stat Mean",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "AVERAGEX(",
              "    VALUES('Stats'[CharacterId]), // Iterate over each unique character",
              "    CALCULATE(",
              "        SUM('Stats'[ATK]) + ",
              "        SUM('Stats'[DEF]) + ",
              "        SUM('Stats'[HP]) + ",
              "        SUM('Stats'[Speed]),",
              "        FILTER('Stats', 'Stats'[CharacterId] = EARLIER('Stats'[CharacterId]) && 'Stats'[Level_Id] = MAX('Stats'[Level_Id]))",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "e76f4680-d74e-4ee8-a89b-fcbfbe3c6469"
          },
          {
            "name": "MAX ATK MEAN",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "AVERAGEX(",
              "    VALUES('Stats'[CharacterId]), ",
              "    CALCULATE(",
              "        MAX('Stats'[ATK]",
              "    )",
              "))"
            ],
            "lineageTag": "f2c09233-15cc-456a-9561-ddd021682aa7"
          },
          {
            "name": "MAX DEF MEAN",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "AVERAGEX(",
              "    VALUES('Stats'[CharacterId]), ",
              "    CALCULATE(",
              "        MAX('Stats'[DEF]",
              "    )",
              "))"
            ],
            "lineageTag": "f2b0242b-ce2a-43ae-b425-08b8fd5ae21f"
          },
          {
            "name": "MAX SPD MEAN",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "AVERAGEX(",
              "    VALUES('Stats'[CharacterId]), ",
              "    CALCULATE(",
              "        MAX('Stats'[Speed]",
              "    )",
              "))"
            ],
            "lineageTag": "37051826-a8b0-4199-a3dd-03d3e107ab02"
          },
          {
            "name": "MAX HP MEAN",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "AVERAGEX(",
              "    VALUES('Stats'[CharacterId]), ",
              "    CALCULATE(",
              "        MAX('Stats'[HP]",
              "    )",
              "))"
            ],
            "lineageTag": "2081b5af-e126-412a-aa57-b3ad7754b8be"
          }
        ],
        "partitions": [
          {
            "name": "Stats",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"D:\\DA\\Honkai Star Rail Fun Insights from Data Analysis\\Honkai-Star-Rail-A-Few-Fun-Insights-with-Data-Analysis\\hsr\\hsr_updated\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (2)\", each #\"Transform File (2)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (2)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample File (2)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Level\", Int64.Type}, {\"HP\", Int64.Type}, {\"ATK\", Int64.Type}, {\"DEF\", Int64.Type}, {\"Speed\", Int64.Type}, {\"ATK Growth\", Int64.Type}, {\"ATK Growth %\", type number}, {\"DEF Growth\", Int64.Type}, {\"DEF Growth %\", type number}, {\"HP Growth\", Int64.Type}, {\"HP Growth %\", type number}, {\"Speed Growth\", Int64.Type}, {\"Speed Growth %\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\".xlsx\",\"\",Replacer.ReplaceText,{\"Source.Name\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Replaced Value\", {\"Source.Name\"}, Characters, {\"Character\"}, \"Characters\", JoinKind.LeftOuter),",
                "    #\"Expanded Characters\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Characters\", {\"CharacterId\"}, {\"Characters.CharacterId\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Characters\",{{\"Characters.CharacterId\", \"CharacterId\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"CharacterId\", \"Source.Name\", \"Level\", \"HP\", \"ATK\", \"DEF\", \"Speed\", \"ATK Growth\", \"ATK Growth %\", \"DEF Growth\", \"DEF Growth %\", \"HP Growth\", \"HP Growth %\", \"Speed Growth\", \"Speed Growth %\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"Source.Name\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Removed Columns\", {\"Level\"}, Level, {\"Level\"}, \"Level.1\", JoinKind.LeftOuter),",
                "    #\"Expanded Level.1\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Level.1\", {\"Level_Id\"}, {\"Level.1.Level_Id\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Expanded Level.1\", each true),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Level.1.Level_Id\", \"Level_Id\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns2\",{\"Level\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Columns1\",{\"CharacterId\", \"Level_Id\", \"HP\", \"ATK\", \"DEF\", \"Speed\", \"ATK Growth\", \"ATK Growth %\", \"DEF Growth\", \"DEF Growth %\", \"HP Growth\", \"HP Growth %\", \"Speed Growth\", \"Speed Growth %\"})",
                "in",
                "    #\"Reordered Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Level",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Level_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "d43178d9-8e88-44af-b6a7-c6b384fa1077",
            "sourceColumn": "Level_Id",
            "summarizeBy": "none"
          },
          {
            "name": "Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e6aa2e4b-ba03-4b15-91b0-eb42ea7f3b6f",
            "sourceColumn": "Level",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a273d628-c2ec-4337-a85d-999e8b353f81",
        "partitions": [
          {
            "name": "Level",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"D:\\DA\\Honkai Star Rail Fun Insights from Data Analysis\\Honkai-Star-Rail-A-Few-Fun-Insights-with-Data-Analysis\\hsr\\hsr_updated\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (2)\", each #\"Transform File (2)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (2)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample File (2)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Level\", Int64.Type}, {\"HP\", Int64.Type}, {\"ATK\", Int64.Type}, {\"DEF\", Int64.Type}, {\"Speed\", Int64.Type}, {\"ATK Growth\", Int64.Type}, {\"ATK Growth %\", type number}, {\"DEF Growth\", Int64.Type}, {\"DEF Growth %\", type number}, {\"HP Growth\", Int64.Type}, {\"HP Growth %\", type number}, {\"Speed Growth\", Int64.Type}, {\"Speed Growth %\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\".xlsx\",\"\",Replacer.ReplaceText,{\"Source.Name\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Replaced Value\", {\"Source.Name\"}, Characters, {\"Character\"}, \"Characters\", JoinKind.LeftOuter),",
                "    #\"Expanded Characters\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Characters\", {\"CharacterId\"}, {\"Characters.CharacterId\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded Characters\",{\"Characters.CharacterId\", \"Source.Name\", \"Level\", \"HP\", \"ATK\", \"DEF\", \"Speed\", \"ATK Growth\", \"ATK Growth %\", \"DEF Growth\", \"DEF Growth %\", \"HP Growth\", \"HP Growth %\", \"Speed Growth\", \"Speed Growth %\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Characters.CharacterId\", \"CharacterId\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Source.Name\", \"HP\", \"ATK\", \"DEF\", \"Speed\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"StatsGrowthId\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns2\",{\"StatsGrowthId\", \"CharacterId\", \"Level\", \"ATK Growth\", \"ATK Growth %\", \"DEF Growth\", \"DEF Growth %\", \"HP Growth\", \"HP Growth %\", \"Speed Growth\", \"Speed Growth %\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"StatsGrowthId\", \"CharacterId\", \"ATK Growth\", \"ATK Growth %\", \"DEF Growth\", \"DEF Growth %\", \"HP Growth\", \"HP Growth %\", \"Speed Growth\", \"Speed Growth %\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns1\"),",
                "    #\"Added Index1\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index1\",{{\"Index\", \"Level_Id\"}}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Renamed Columns3\",{\"Level_Id\", \"Level\"})",
                "in",
                "    #\"Reordered Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}